import { QuizQuestion } from "./types";

// Bank soal Cerdas Cermat — trivia Indonesia.
// Bagian 1: geografi. Bagian 2 (budaya & umum) menyusul di bawah.
export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ---- GEOGRAFI ----
  { q: "Ibu kota provinsi Sulawesi Selatan?", choices: ["Manado", "Makassar", "Palu", "Kendari"], answer: 1, topic: "geografi" },
  { q: "Gunung tertinggi di Indonesia?", choices: ["Semeru", "Rinjani", "Puncak Jaya", "Kerinci"], answer: 2, topic: "geografi" },
  { q: "Pulau terbesar di Indonesia?", choices: ["Sumatera", "Jawa", "Sulawesi", "Kalimantan"], answer: 3, topic: "geografi" },
  { q: "Danau terbesar di Indonesia?", choices: ["Danau Toba", "Danau Maninjau", "Danau Singkarak", "Danau Sentani"], answer: 0, topic: "geografi" },
  { q: "Ibu kota provinsi Papua?", choices: ["Manokwari", "Sorong", "Jayapura", "Merauke"], answer: 2, topic: "geografi" },
  { q: "Selat yang memisahkan Jawa dan Sumatera?", choices: ["Selat Sunda", "Selat Bali", "Selat Makassar", "Selat Karimata"], answer: 0, topic: "geografi" },
  { q: "Provinsi paling barat Indonesia?", choices: ["Sumatera Utara", "Aceh", "Sumatera Barat", "Riau"], answer: 1, topic: "geografi" },
  { q: "Ibu kota Kalimantan Timur?", choices: ["Balikpapan", "Pontianak", "Samarinda", "Banjarmasin"], answer: 2, topic: "geografi" },
  { q: "Gunung berapi di antara Jawa dan Sumatera yang meletus dahsyat 1883?", choices: ["Tambora", "Krakatau", "Merapi", "Galunggung"], answer: 1, topic: "geografi" },
  { q: "Ibu kota negara Indonesia yang baru (IKN)?", choices: ["Nusantara", "Penajam", "Sepaku", "Balikpapan Baru"], answer: 0, topic: "geografi" },
  { q: "Pulau yang dijuluki 'Pulau Dewata'?", choices: ["Lombok", "Bali", "Flores", "Sumba"], answer: 1, topic: "geografi" },
  { q: "Sungai terpanjang di Indonesia?", choices: ["Sungai Musi", "Sungai Mahakam", "Sungai Kapuas", "Bengawan Solo"], answer: 2, topic: "geografi" },
  { q: "Ibu kota Nusa Tenggara Timur?", choices: ["Mataram", "Kupang", "Ende", "Labuan Bajo"], answer: 1, topic: "geografi" },
  { q: "Taman nasional habitat asli komodo?", choices: ["TN Komodo", "TN Baluran", "TN Ujung Kulon", "TN Way Kambas"], answer: 0, topic: "geografi" },
  { q: "Kota yang dijuluki 'Kota Pahlawan'?", choices: ["Jakarta", "Bandung", "Surabaya", "Semarang"], answer: 2, topic: "geografi" },
  { q: "Kota yang dijuluki 'Kota Kembang'?", choices: ["Bogor", "Malang", "Bandung", "Yogyakarta"], answer: 2, topic: "geografi" },
  { q: "Provinsi penghasil rendang, masakan terenak dunia?", choices: ["Sumatera Barat", "Aceh", "Riau", "Jambi"], answer: 0, topic: "geografi" },
  { q: "Jumlah provinsi di Indonesia saat ini?", choices: ["33", "34", "38", "40"], answer: 2, topic: "geografi" },
  { q: "Laut di utara Pulau Jawa?", choices: ["Laut Banda", "Laut Jawa", "Laut Arafura", "Laut Flores"], answer: 1, topic: "geografi" },
  { q: "Ibu kota Sulawesi Utara?", choices: ["Gorontalo", "Palu", "Manado", "Tomohon"], answer: 2, topic: "geografi" },

  // ---- BUDAYA ----
  { q: "Tari Kecak berasal dari?", choices: ["Jawa Barat", "Bali", "Sumatera Utara", "Sulawesi Selatan"], answer: 1, topic: "budaya" },
  { q: "Rumah adat Minangkabau?", choices: ["Joglo", "Rumah Gadang", "Tongkonan", "Honai"], answer: 1, topic: "budaya" },
  { q: "Alat musik tradisional dari Jawa Barat yang digoyang?", choices: ["Sasando", "Angklung", "Kolintang", "Tifa"], answer: 1, topic: "budaya" },
  { q: "Lagu 'Ampar-Ampar Pisang' berasal dari?", choices: ["Kalimantan Selatan", "Sulawesi Utara", "Maluku", "Papua"], answer: 0, topic: "budaya" },
  { q: "Rumah adat Toraja disebut?", choices: ["Rumah Gadang", "Tongkonan", "Joglo", "Lamin"], answer: 1, topic: "budaya" },
  { q: "Wayang kulit paling identik dengan budaya?", choices: ["Betawi", "Jawa", "Dayak", "Bugis"], answer: 1, topic: "budaya" },
  { q: "Tari Saman yang mendunia berasal dari?", choices: ["Aceh", "Padang", "Palembang", "Lampung"], answer: 0, topic: "budaya" },
  { q: "Batik diakui UNESCO sebagai warisan budaya pada tahun?", choices: ["2005", "2009", "2012", "2015"], answer: 1, topic: "budaya" },
  { q: "Alat musik Sasando berasal dari?", choices: ["NTT", "NTB", "Maluku", "Sulawesi Tenggara"], answer: 0, topic: "budaya" },
  { q: "Upacara pembakaran jenazah di Bali disebut?", choices: ["Ngaben", "Kasada", "Rambu Solo", "Tabuik"], answer: 0, topic: "budaya" },
  { q: "Senjata tradisional khas Jawa?", choices: ["Rencong", "Mandau", "Keris", "Badik"], answer: 2, topic: "budaya" },
  { q: "Tari Piring berasal dari?", choices: ["Sumatera Barat", "Jambi", "Bengkulu", "Riau"], answer: 0, topic: "budaya" },
  { q: "Lagu daerah 'Apuse' berasal dari?", choices: ["Maluku", "Papua", "NTT", "Sulawesi Utara"], answer: 1, topic: "budaya" },
  { q: "Rumah adat Papua?", choices: ["Honai", "Lamin", "Gapura", "Bale"], answer: 0, topic: "budaya" },
  { q: "Angklung diakui UNESCO tahun?", choices: ["2008", "2010", "2013", "2016"], answer: 1, topic: "budaya" },
  { q: "Makanan khas Palembang yang terkenal?", choices: ["Gudeg", "Pempek", "Rawon", "Coto"], answer: 1, topic: "budaya" },
  { q: "Gudeg adalah makanan khas?", choices: ["Solo", "Semarang", "Yogyakarta", "Magelang"], answer: 2, topic: "budaya" },
  { q: "Suku asli Kalimantan yang terkenal?", choices: ["Asmat", "Dayak", "Badui", "Sasak"], answer: 1, topic: "budaya" },
  { q: "Pencak silat diakui UNESCO sebagai warisan budaya tahun?", choices: ["2017", "2019", "2021", "2023"], answer: 1, topic: "budaya" },
  { q: "Kain tenun ikat Sumba berasal dari provinsi?", choices: ["NTB", "NTT", "Maluku", "Bali"], answer: 1, topic: "budaya" },

  // ---- UMUM ----
  { q: "Proklamator kemerdekaan Indonesia?", choices: ["Soekarno-Hatta", "Soeharto-Habibie", "Sjahrir-Tan Malaka", "Soedirman-Nasution"], answer: 0, topic: "umum" },
  { q: "Indonesia merdeka pada tanggal?", choices: ["17 Agustus 1944", "17 Agustus 1945", "18 Agustus 1945", "1 Juni 1945"], answer: 1, topic: "umum" },
  { q: "Pencipta lagu Indonesia Raya?", choices: ["Ismail Marzuki", "W.R. Supratman", "C. Simanjuntak", "Ibu Sud"], answer: 1, topic: "umum" },
  { q: "Pahlawan wanita dari Jepara pejuang emansipasi?", choices: ["Cut Nyak Dien", "Kartini", "Dewi Sartika", "Martha Tiahahu"], answer: 1, topic: "umum" },
  { q: "Sumpah Pemuda diikrarkan tahun?", choices: ["1908", "1928", "1945", "1949"], answer: 1, topic: "umum" },
  { q: "Lambang negara Indonesia?", choices: ["Garuda Pancasila", "Elang Jawa", "Cendrawasih", "Rajawali"], answer: 0, topic: "umum" },
  { q: "Presiden ke-3 Indonesia?", choices: ["Soeharto", "B.J. Habibie", "Gus Dur", "Megawati"], answer: 1, topic: "umum" },
  { q: "Candi Buddha terbesar di dunia yang ada di Indonesia?", choices: ["Prambanan", "Borobudur", "Mendut", "Sewu"], answer: 1, topic: "umum" },
  { q: "Mata uang Indonesia?", choices: ["Ringgit", "Peso", "Rupiah", "Baht"], answer: 2, topic: "umum" },
  { q: "Semboyan bangsa Indonesia?", choices: ["Bhinneka Tunggal Ika", "Tut Wuri Handayani", "Jalesveva Jayamahe", "Rastra Sewakottama"], answer: 0, topic: "umum" },
  { q: "Pahlawan dari Aceh yang gigih melawan Belanda?", choices: ["Pattimura", "Cut Nyak Dien", "Diponegoro", "Imam Bonjol"], answer: 1, topic: "umum" },
  { q: "Hari Pendidikan Nasional diperingati tiap?", choices: ["2 Mei", "20 Mei", "1 Juni", "17 Agustus"], answer: 0, topic: "umum" },
  { q: "Organisasi pergerakan nasional pertama (1908)?", choices: ["Sarekat Islam", "Budi Utomo", "Indische Partij", "PNI"], answer: 1, topic: "umum" },
  { q: "Hewan langka khas Ujung Kulon?", choices: ["Harimau Sumatera", "Badak Jawa", "Orangutan", "Anoa"], answer: 1, topic: "umum" },
  { q: "Bunga nasional Indonesia (puspa bangsa)?", choices: ["Anggrek Bulan", "Melati Putih", "Rafflesia", "Kenanga"], answer: 1, topic: "umum" },
  { q: "Perang Diponegoro berlangsung tahun?", choices: ["1825-1830", "1815-1820", "1830-1835", "1840-1845"], answer: 0, topic: "umum" },
  { q: "Bapak Koperasi Indonesia?", choices: ["Soekarno", "Mohammad Hatta", "Ki Hajar Dewantara", "Sutomo"], answer: 1, topic: "umum" },
  { q: "Tim bulu tangkis Indonesia merebut Piala Thomas pertama kali tahun?", choices: ["1958", "1961", "1964", "1970"], answer: 0, topic: "umum" },
  { q: "Satelit pertama Indonesia?", choices: ["Palapa A1", "Telkom-1", "Garuda-1", "Merah Putih"], answer: 0, topic: "umum" },
  { q: "Pulau yang dijuluki 'serpihan surga' dengan Raja Ampat?", choices: ["Maluku", "Papua Barat Daya", "Sulawesi Utara", "NTT"], answer: 1, topic: "umum" },
];
